### PR TITLE
Automate Network Release 

### PR DESCRIPTION
**Pull request by narayanprusty**
Sample command:

```
go-spacecraft releaseNetwork --go-sm-release-version=v0.2.6-beta.0 --network-name=devnet210
```

### CODE REVIEW

**Comment by moshababo** [comment]
I assume we need to relate to a specific already-running network, for having its dynamically-generated config file. If so, we do we need to specify `--go-sm-release-version`? Isn't it already set by the chosen network?

**Comment by moshababo** [comment]
I assume we need to relate to a specific, already-running network, for having its dynamically-generated config file. If so, why do we need to specify `--go-sm-release-version`? Isn't it already set by the chosen network?

**Comment by narayanprusty** [comment]
> I assume we need to relate to a specific, already-running network, for having its dynamically-generated config file. If so, why do we need to specify `--go-sm-release-version`? Isn't it already set by the chosen network?

@moshababo We cannot get the go-spacemesh release version using the network name. When creating a network we nowhere store the release version associated to it. We only provide a docker image and the docker image has only the commit hash as the tag.

**Comment by moshababo** [comment]
Since this can lead to mistakes, and since the `go-spacemesh` release is required for releasing it in `sm-net` (and also, useful to inspect in discovery), I'm wondering whether we can just use that instead of a docker image, while the image (for K8s) can be published in the release notes. In addition, we can still allow network deployments using merely an image, for testing, but these aren't release-able to `sm-net`.

What do you think?

**Comment by narayanprusty** [comment]
To use a release version instead of docker image when creating a network will create limitations. We will end up having networks only for releases and devs cannot pick a random commit and test. I don't think we need to make any changes in spacecraft to support both docker image and release version during network creation we can just create a docker image with tag same as release version and use that. This can be done in the go-spacemesh GHA pipeline.

I think in future we will have multiple release versions for a single network. We can release go-spacemesh builds with fixes/patches for an existing network. So if releaseNetwork sub-command takes releaseVersion then this is possible. Similarly we can take take a patched docker image and test with managed miners.

I suggest we keep it this way currently as it gives us a lot of flexibility. We can get back to this later and make changes if necessary.

**Review by moshababo — APPROVED** [review]

**Pull request merged**
